[package]
name = "create-rust-app-template"
version = "0.1.0"
authors = ["joy <joy.lai@zg.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
